# Generated by Django 3.2.7 on 2021-10-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('sub_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('price_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.PositiveSmallIntegerField(choices=[('extra small', 0), ('small', 1), ('medium', 2), ('large', 3), ('extra large', 4)])),
                ('color', models.CharField(max_length=25)),
                ('unit_in_stock', models.PositiveIntegerField()),
                ('ranking', models.PositiveIntegerField(choices=[('Very Bad', 1), ('Bad', 2), ('Not Bad', 3), ('Good', 4), ('Very Good', 5)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
        ),
    ]
