# Generated by Django 3.2.7 on 2021-10-15 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('price_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.CharField(choices=[('extra small', 'extras small'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('extra large', 'extra large')], max_length=30)),
                ('color', models.CharField(max_length=25)),
                ('unit_in_stock', models.PositiveIntegerField()),
                ('ranking', models.CharField(choices=[('Very Bad', 'Very Bad'), ('Bad', 'Bad'), ('Not Bad', 'Not Bad'), ('Good', 'Good'), ('Very Good', 'Very Good')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
