# Generated by Django 3.2.7 on 2021-10-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_detail',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_detail',
            field=models.ManyToManyField(to='orders.OrderItem'),
        ),
    ]
