# Generated by Django 3.2.7 on 2021-10-15 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211015_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.AddField(
            model_name='shipment',
            name='price',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.shipment'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipment_price',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
