# Generated by Django 3.2.7 on 2021-10-15 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='shipment_price',
        ),
    ]
